### ISSUE TITLE
Calculation of alpha values computes sin(sin(angle))

### ISSUE THREAD

**Issue by possibly-wrong** [UniBwTAS/ccma#2]
Thanks for a very interesting paper, and very readable implementation! I'm reviewing your paper, and trying to reconcile the description there of the calculation of the angles $\alpha_k$ (referencing Figure 2) with the corresponding implementation here:

https://github.com/UniBwTAS/ccma/blob/75e4fe3ad32a02be1718634163a47f84e360fbf1/ccma/ccma.py#L251

I think this should be `alphas[idx] = asin(dist_neighbors / 2) / radius`, without the `sin`, correct? Since the **argument** to the `sin()` is effectively "already" the sine of the angle between the vectors $p_i-p_{i-1}$ and $p_{i+1}-p_i$. That is, the argument may be computed as the norm/magnitude of the cross product between these two vectors, normalized/divided by their magnitudes.

**Comment by AutonomousTommy** [comment]
Hi,

Thank you very much for your interest and for sharing your insights and suggestions!

You are correct that the calculation was incorrect; however, instead of using sine, arcsine is required. The attached figure explains the calculation in more detail.

The calculation in the code has now been fixed.

![alpha_calculation](https://github.com/user-attachments/assets/12a5cfbf-7b65-4200-9182-f5102c1762ea)
